import "./globals.css";
import Menu from "@/components/Menu/Menu";

export const metadata = {
  title: "Abm test",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <header>
          {/* <nav><Menu/></nav> */}
        </header>
        <main>
          {children}
        </main>
        <footer>
          Footer
        </footer>
      </body>
    </html>
  );
}
